# : replace the title with the name of your restaurant!
title: "Data Exploration Blog"
# : write your restaurateur alter ego name below, or your own name
author: 
# : write your Google Analytics tracking ID below
google_analytics: G-30QRQYPJX7

theme: minima

collections:
  explorations:
    output: true
